export const REQUEST_AFFILIATIONS = 'REQUEST_AFFILIATIONS'
export const UPDATE_AFFILIATIONS = 'UPDATE_AFFILIATIONS'
export const TOGGLE_AFFILIATION = 'TOGGLE_AFFILIATION'
export const TOGGLE_SHOWING_CURRENT = 'TOGGLE_SHOWING_CURRENT'
