export const REQUEST_CURRENT_BUSINESS = 'REQUEST_CURRENT_BUSINESS'
export const REQUEST_CURRENT_BUSINESS_SUCCESS = 'REQUEST_CURRENT_BUSINESS_SUCCESS'
export const REQUEST_CURRENT_BUSINESS_ERROR = 'REQUEST_CURRENT_BUSINESS_ERROR'
