export const REQUEST_AFFILIATIONS_LOADING = 'REQUEST_AFFILIATIONS_LOADING'
export const REQUEST_AFFILIATIONS_SUCCESS = 'REQUEST_AFFILIATIONS_SUCCESS'
export const REQUEST_AFFILIATIONS_ERROR = 'REQUEST_STATUS_CURRENT_BUSINESS_ERROR'
