export const AUTH_STATUS_INITIAL = 'AUTH_INITIAL'
export const AUTH_STATUS_LOADING = 'AUTH_LOADING'
export const AUTH_STATUS_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_STATUS_ERROR_CREDENTIALS = 'AUTH_STATUS_ERROR_CREDENTIALS'

export const REGISTER_STATUS_INITIAL = 'REGISTER_STATUS_INITIAL'
export const REGISTER_STATUS_LOADING = 'REGISTER_STATUS_LOADING'
export const REGISTER_STATUS_SUCCESS = 'REGISTER_STATUS_SUCCESS'
export const REGISTER_STATUS_ERROR_CREDENTIALS = 'REGISTER_STATUS_ERROR_CREDENTIALS'
