export const AUTH_STATUS_INITIAL = 'AUTH_INITIAL'
export const AUTH_STATUS_LOADING = 'AUTH_LOADING'
export const AUTH_STATUS_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_STATUS_ERROR_CREDENTIALS = 'AUTH_STATUS_ERROR_CREDENTIALS'
